### ISSUE TITLE
Fix the analysis script

### ISSUE THREAD

**Issue by spiderbaby** [Kortemme-Lab/loop_modeling#4]
The analysis/analysis.py script uses the tools package which has now been renamed to https://github.com/Kortemme-Lab/klab.
1. "pip install -e git+ssh://git@github.com/Kortemme-Lab/klab.git#egg=klab" in the virtual environment containing the loop_modeling clone
2. Fix the analysis.py script to use klab rather than tools.
3. Update the main documentation to tell users to install the klab package as a dependency.

**Comment by xingjiepan** [comment]
Now the analyze.py script will automatically ask the user to install klab.
